### ISSUE TITLE
Error in use library

### ISSUE THREAD

**Issue by daraboon** [waitingsong/node-windows-window-controller#2]
Hi
I pkg my project with "pkg library" and try to use this library but there are errors
Please help to me for solve it
Thanks

Error: The module '\\?\C:\wamp64\www\Patriot\robot\node_modules\ref\build\Release\binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:680:18)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/module.js:11:18)
    at bindings (C:\snapshot\robot\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\snapshot\robot\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)

**Comment by waitingsong** [comment]
What's the version of your python?
